# Generated by Django 3.0.4 on 2021-02-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=200)),
                ('Contenido', models.TextField()),
                ('FechaPub', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
