# Generated by Django 3.0.4 on 2021-02-16 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='FechaPub',
            new_name='Publicado',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Titulo',
            new_name='Título',
        ),
    ]
