# Generated by Django 3.0.4 on 2021-02-22 21:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Inversión', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Fecha', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
